#!/bin/bash

# Set command line prompt
export project_name="ITE_IAA"

# Call appropriate functions from ~/.functions
source "$HOME/.functions"
tb_webppl

# Set directory aliases
alias phome="cd /om/user/daeda/ite_iaa/ite_gb_inverseappraisal/code"
cd /om/user/daeda/ite_iaa/ite_gb_inverseappraisal || exit
conda activate envs/default
cd code || exit
